allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  mongodb-memory-server: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - icu-minify@4.14.7
  - next-intl-swc-plugin-extractor@4.14.7
  - next-intl@4.14.7
  - use-intl@4.14.7
